- name: my first ansible playbook
  hosts: apps
  become: true
  tasks:
    - name: Apache2 Install
      apt:
        name: apache2
        state: present

    - name: Create a Directory
      file:
        path: /home/jenkins/demo
        owner: jenkins
       
    - name: Create a File
      file:
        path: /home/jenkins/demo/demo.txt
        owner: jenkins
    - name: Add contents to demo.txt file
      copy:
        dest: /home/jenkins/demo/demo.txt
        content: 'Hello World, Devops learning is fun'

