- name: my first ansible playbook
  hosts: apps
  become: true
  tasks:
    - name: Apache2 Install
      apt:
        name: apache2
        state: present

    - name: Create a Directory
      file:
        path: /home/jenkins/demo
        owner: jenkins
       
    - name: Create a File
      file:
        path: /home/jenkins/demo/demo.txt
        owner: jenkins
    - name: Add contents to demo.txt file
      copy:
        dest: /home/jenkins/demo/demo.txt
        content: 'Hello World, Devops learning is fun'
    - name: Add few more lines to same file
      lineinfile:
        path: /home/jenkins/demo/demo.txt
        line: 'Lets spend time learning DevOps!!!'
    - name: Download Ops-Agent package
      get_url:
        url: https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
        dest: /tmp
        mode: 0755
    - name: Install Ops Agent on managed node
      command: /tmp/add-google-cloud-ops-agent-repo.sh --also-install
    - name: Create Vol Grp
      lvg:
        vg: data_vg
        pvs: /dev/sdb
    - name: Create Log Vol
      lvol:
        vg: data_vg
        lv: data_lv
        size: 5g
        state: present
    - name: Filesystem Type
      filesystem:
        dev: /dev/data_vg/data_lv
        fstype: xfs
    - name: Mount FS on directory
      mount:
        src: /dev/data-vg-data_lv
        fstype: xfs
        state: mounted
        path: /data





